# Generated by Django 4.2.7 on 2024-01-09 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='school',
            old_name='renteremail',
            new_name='confirmemail',
        ),
    ]
